version: 1.0
name: ipmi
debug: true
network:
  type: tcp
  address: ":5001"
settings:
  mode: parallel
  read:
    interval: 3s
  write:
    interval: 1s
auto_enumerate:
  - hostname: ipmisim
    port: 623
    username: ADMIN
    password: ADMIN
    interface: lanplus
